import type { PricingPlan } from "@/types/pricing.types";

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "For photographers exploring AI-powered culling.",
    monthlyPrice: 0,
    annualPrice: 0,
    ctaLabel: "Download Free",
    ctaHref: "/download",
    features: [
      { label: "Up to 500 images/month", included: true },
      { label: "AI Image Culling", included: true },
      { label: "Technical Quality Analysis", included: true },
      { label: "Basic Sorting (4 categories)", included: true },
      { label: "JPEG & RAW support", included: true },
      { label: "Aesthetic Analysis", included: false },
      { label: "Batch Processing", included: false },
      { label: "Lightroom Recipe Export", included: false },
      { label: "AI Editing Engine", included: false },
      { label: "Cloud Sync", included: false },
      { label: "Priority Support", included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "For working photographers who need full AI power.",
    monthlyPrice: 19,
    annualPrice: 15,
    highlighted: true,
    badge: "Most Popular",
    ctaLabel: "Get Pro",
    ctaHref: "/register",
    features: [
      { label: "Unlimited images", included: true },
      { label: "AI Image Culling", included: true },
      { label: "Technical Quality Analysis", included: true },
      { label: "Full Sorting (8 categories)", included: true },
      { label: "JPEG & RAW support", included: true },
      { label: "Aesthetic Analysis", included: true },
      { label: "Batch Processing", included: true },
      { label: "Lightroom Recipe Export", included: true },
      { label: "AI Editing Engine", included: true },
      { label: "Cloud Sync (50GB)", included: true },
      { label: "Priority Support", included: false },
    ],
  },
  {
    id: "studio",
    name: "Studio",
    description: "For photography studios and professional teams.",
    monthlyPrice: 49,
    annualPrice: 39,
    ctaLabel: "Get Studio",
    ctaHref: "/register",
    features: [
      { label: "Unlimited images", included: true },
      { label: "AI Image Culling", included: true },
      { label: "Technical Quality Analysis", included: true },
      { label: "Full Sorting + Custom Categories", included: true },
      { label: "JPEG & RAW support", included: true },
      { label: "Aesthetic Analysis", included: true },
      { label: "Batch Processing", included: true },
      { label: "Lightroom Recipe Export", included: true },
      { label: "AI Editing Engine", included: true },
      { label: "Cloud Sync (500GB)", included: true },
      { label: "Priority Support", included: true },
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Custom solutions for media companies and large teams.",
    monthlyPrice: null,
    annualPrice: null,
    ctaLabel: "Contact Sales",
    ctaHref: "/contact",
    features: [
      { label: "Everything in Studio", included: true },
      { label: "Custom AI model training", included: true },
      { label: "On-premise deployment", included: true },
      { label: "API access", included: true },
      { label: "Team collaboration", included: true },
      { label: "Unlimited cloud storage", included: true },
      { label: "SLA & dedicated support", included: true },
      { label: "Custom integrations", included: true },
      { label: "Compliance & security review", included: true },
      { label: "Custom contracts", included: true },
      { label: "24/7 Priority Support", included: true },
    ],
  },
];
